<template><h2 id="repository-initialization" tabindex="-1"><a class="header-anchor" href="#repository-initialization" aria-hidden="true">#</a> Repository initialization</h2>
<p>⚠️ If you don't care about automatic versioning and just want to use <code>coco</code> to create conventional commits
you can skip this section and jump to the next one.</p>
<p>To get the most out of cocogitto you need to have a <code>cog.toml</code> config at the root of your repository.
You can create this file manually or generate the default one with <code>cog init</code>.</p>
<p>The default config file generated by cog init looks like this.
You can read the configuration reference for more information.</p>
<div class="language-toml ext-toml"><pre v-pre class="language-toml"><code><span class="token key property">changelog_path</span> <span class="token punctuation">=</span> <span class="token string">"CHANGELOG.md"</span>
<span class="token key property">pre_bump_hooks</span> <span class="token punctuation">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token key property">post_bump_hooks</span> <span class="token punctuation">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token key property">authors</span> <span class="token punctuation">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>

<span class="token punctuation">[</span><span class="token table class-name">commit_types</span><span class="token punctuation">]</span>
</code></pre></div><h2 id="creating-a-new-repository" tabindex="-1"><a class="header-anchor" href="#creating-a-new-repository" aria-hidden="true">#</a> Creating a new repository</h2>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code><span class="token function">mkdir</span> my_repo <span class="token operator">&amp;&amp;</span> <span class="token builtin class-name">cd</span> my_repo
cog init
</code></pre></div><p><code>cog init</code> works like <code>git init</code> except it create a template <code>cog.toml</code> config file,
and a default initial commit with the following message : <code>chore: initial commit</code>.</p>
<p>Optionally you can specify the target path of the repository you want to create :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>cog init my_repo
</code></pre></div><h2 id="initializing-an-existing-repo" tabindex="-1"><a class="header-anchor" href="#initializing-an-existing-repo" aria-hidden="true">#</a> Initializing an existing repo</h2>
<p>Running <code>cog init</code> on an existing repository will just create a template configuration without creating any commit :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code><span class="token function">git</span> init my_repo <span class="token operator">&amp;&amp;</span> <span class="token builtin class-name">cd</span> my_repo
cog init
</code></pre></div><div class="language-text ext-text"><pre v-pre class="language-text"><code>❯ git status
On branch master
Changes to be committed:
  (use "git restore --staged &lt;file>..." to unstage)
	new file:   cog.toml
</code></pre></div><h2 id="conventional-commits" tabindex="-1"><a class="header-anchor" href="#conventional-commits" aria-hidden="true">#</a> Conventional commits</h2>
<p><code>coco</code> allows you to easily create commits respecting the
<a href="https://www.conventionalcommits.org/en/v1.0.0/" target="_blank" rel="noopener noreferrer">conventional commits specification<OutboundLink/></a>. It comes with a set of predefined
arguments named after conventional commit types and
<a href="https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines" target="_blank" rel="noopener noreferrer">Angular commit convention<OutboundLink/></a>
:  <code>feat</code>, <code>fix</code>, <code>style</code>, <code>build</code>, <code>refactor</code>, <code>ci</code>, <code>test</code>, <code>perf</code>, <code>chore</code>, <code>revert</code>, <code>docs</code>.</p>
<p>As described in the specification conventional commits messages are structured as follows :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>&lt;type>[optional scope]: &lt;description>

[optional body]

[optional footer(s)]
</code></pre></div><p>All <code>coco</code> commit type subcommands follows the same structure :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>coco <span class="token punctuation">{</span>type<span class="token punctuation">}</span> <span class="token punctuation">{</span>message<span class="token punctuation">}</span> <span class="token punctuation">[</span>optional scope<span class="token punctuation">]</span> <span class="token punctuation">[</span>optional body<span class="token punctuation">]</span> <span class="token punctuation">[</span>optional footer<span class="token punctuation">]</span>
</code></pre></div><p>You need to remember that <code>coco</code> commit scope comes after the commit description.
This allows using positional arguments instead of typing flags (ex: <code>coco -t {type} -s {scope} -m {message}... and so on</code>).</p>
<p><strong>Example :</strong>
If you want to create the following commit : <code>feat: add awesome feature</code> :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>coco feat <span class="token string">"add awesome feature"</span>
</code></pre></div><h3 id="helpful-error-messages" tabindex="-1"><a class="header-anchor" href="#helpful-error-messages" aria-hidden="true">#</a> Helpful error messages</h3>
<p>Using <code>coco</code> should prevent a wide range of error in your conventional commit message. But if you still made a mistake
<code>coco</code> will display an error explaining what went wrong :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>❯ coco feat "add ability to parse arrays" "sco(pe"
Error: A scope value cannot contains inner parenthesis

Caused by:
     --> 1:9
      |
    1 | feat(sco(pe): add ability to parse arrays
      |         ^---
      |
      = expected no_parenthesis
</code></pre></div><h3 id="breaking-changes" tabindex="-1"><a class="header-anchor" href="#breaking-changes" aria-hidden="true">#</a> Breaking changes</h3>
<p>All <code>coco</code> argument are positional except the optional <code>-B</code> flag used to create breaking changes commits :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>coco fix -B <span class="token string">"add fix a nasty bug"</span> cli
</code></pre></div><p>This would create the following <a href="https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with--to-draw-attention-to-breaking-change" target="_blank" rel="noopener noreferrer">breaking change<OutboundLink/></a>
commit : <code>fix(cli)!: fix a nasty bug</code>.</p>
<p><code>coco</code> use the <code>!</code> notation to denote breaking changes commit because it can be easily seen in your git log, however if
you manually create breaking changes commits with <a href="https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer" target="_blank" rel="noopener noreferrer">the footer notation<OutboundLink/></a>
cocogitto tools will still pick them.</p>
<h1 id="managing-commit-history" tabindex="-1"><a class="header-anchor" href="#managing-commit-history" aria-hidden="true">#</a> Managing commit history</h1>
<p><code>cog</code> as several subcommands to examine and manipulate your commit history.</p>
<h2 id="validate-repository-history-compliance-with-the-specification" tabindex="-1"><a class="header-anchor" href="#validate-repository-history-compliance-with-the-specification" aria-hidden="true">#</a> Validate repository history compliance with the specification</h2>
<p>Running <code>cog check</code> will check your commit history against the conventional commit specification :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>❯ cog check
No errored commits
</code></pre></div><p>Let us create an invalid commit :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code><span class="token function">git</span> commit -m <span class="token string">"Your Mother Was A Hamster, And Your Father Smelt Of Elderberries"</span>
</code></pre></div><p>And check our commit history again :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>❯ cog check
Error: ERROR - Your Mother Was A Hamster, And Your Father Smelt Of Elderberries - (c2bb56)
	cause: Missing commit type separator `:
</code></pre></div><p>Additionally, you can check your history, starting from the latest tag to HEAD using <code>from-latest-tag</code> flag.<br>
This is useful when your git repo started to use conventional commits from a certain point in history, and you
don't care about editing old commits.</p>
<h2 id="rewrite-non-compliant-commits" tabindex="-1"><a class="header-anchor" href="#rewrite-non-compliant-commits" aria-hidden="true">#</a> Rewrite non-compliant commits</h2>
<p>Once you have spotted invalid commits you can quickly fix your commit history by running <code>cog edit</code>.
This will perform an automatic rebase and let you edit each malformed commit message with your <code>$EDITOR</code>
of choice.</p>
<p><strong>Example :</strong></p>
<p><code>cog edit</code> will cycle to each malformed commit to rewrite their message :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code># Editing commit c2bb56b93821ff34282f322be4d2231f53b9ada8
# Replace this message with a conventional commit compliant one
# Save and exit to edit the next errored commit
Your Mother Was A Hamster, And Your Father Smelt Of Elderberries
</code></pre></div><div class="custom-container danger"><p class="custom-container-title">DANGER</p>
<p>Using <code>cog edit</code> will modify your commit history and change the commit SHA of edited commit
and their child.</p>
</div>
<h2 id="conventional-commits-git-log" tabindex="-1"><a class="header-anchor" href="#conventional-commits-git-log" aria-hidden="true">#</a> Conventional commits git log</h2>
<p><code>cog log</code> is like <code>git log</code> but it displays additional conventional commit information, such as commit scope,
commit type etc.</p>
<p><a href="https://asciinema.org/a/ssH4yRSlc28Rb9dHEDN7TowGe" target="_blank" rel="noopener noreferrer"><img src="https://asciinema.org/a/ssH4yRSlc28Rb9dHEDN7TowGe.svg" alt="asciicast"><OutboundLink/></a></p>
<p>You can also filter the log content with the following flags (<code>cog log --help</code>) :</p>
<ul>
<li><code>-B</code> : display breaking changes only</li>
<li><code>-t</code> : filter on commit type</li>
<li><code>-a</code> : filter on commit author</li>
<li><code>-s</code> : filter on commit scope</li>
<li><code>-e</code> : ignore errors</li>
</ul>
<p>Those flag can be combined to achieve complex search in your commit history :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>cog log --author <span class="token string">"Paul Delafosse"</span> <span class="token string">"Mike Lubinets"</span> --type feat --scope cli --no-error
</code></pre></div><h3 id="changelog-summary" tabindex="-1"><a class="header-anchor" href="#changelog-summary" aria-hidden="true">#</a> Changelog summary</h3>
<p>There are two ways to generate changelog with <code>cog</code> :</p>
<ul>
<li>
<p>To your repo <code>CHANGELOG.md</code> file with <code>cog bump</code> (see: <RouterLink to="/guide/docs/guide/versioning.mdde/versioning.html#auto-bump">auto bump</RouterLink>)</p>
</li>
<li>
<p>To stdout with <code>cog changelog</code>.</p>
<div class="language-markdown ext-md"><pre v-pre class="language-markdown"><code>❯ cog changelog

<span class="token title important"><span class="token punctuation">##</span> 0.30.0..HEAD - 2020-09-30</span>


<span class="token title important"><span class="token punctuation">###</span> Bug Fixes</span>

7f04a9 - fix ci cross build command bin args - Paul Delafosse

<span class="token title important"><span class="token punctuation">###</span> Features</span>

fc7420 - move check edit to dedicated subcommand and fix rebase - Paul Delafosse
1028d0 - remove config commit on init existing repo - Paul Delafosse

<span class="token title important"><span class="token punctuation">###</span> Refactoring</span>

d4aa61 - change config name to cog.toml - Paul Delafosse
</code></pre></div></li>
</ul>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>You can specify a custom changelog range or tag like so :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code># Display the changelog between `^1` and `2.0.0`
cog changelog --at 2.0.0

# Display the changelog between `8806a5` and `HEAD`
# Note that shortened git oid are not supported yet for this command
cog changelog 8806a55..

# Display the changelog between `8806a5` and `1.0.0`
cog changelog 8806a5..1.0.0
</code></pre></div></div>
<h1 id="automatic-versioning" tabindex="-1"><a class="header-anchor" href="#automatic-versioning" aria-hidden="true">#</a> Automatic versioning</h1>
<p>The purpose of conventional commits is to be able to bump your project version and changelog
automatically. Cocogitto allow you to do this with the <code>cog bump</code> command.</p>
<p>The <code>bump</code> subcommand will execute the following steps :</p>
<ol>
<li>Calculate the next version based on the commit types since the latest tag.</li>
<li>Append the changes for this version to <code>CHANGELOG.md</code>.</li>
<li>Execute a set configuration defined pre-bump hooks.</li>
<li>Create a version commit containing changes made during the previous steps.</li>
<li>Create a git tag on the version commit.</li>
<li>Execute a set of configuration defined post-bump hook.</li>
</ol>
<h3 id="auto-bump" tabindex="-1"><a class="header-anchor" href="#auto-bump" aria-hidden="true">#</a> Auto bump</h3>
<p>Assuming we are working on the following git repository :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>* (HEAD -> master) feat: another cool feature
* docs: add some documentation
* fix: fix ugly bug
* feat: add awesome feature
* chore: initial commit
</code></pre></div><p>Let us now create a version :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>❯ cog bump --auto
Found feature commit caef0f, bumping to 0.1.0
Skipping irrelevant commit 025cc0 with type : docs
Found bug fix commit e2af66, bumping to 0.1.1
Found feature commit 1b87aa, bumping to 0.2.0
Bumped version : 0.0.0 -> 0.2.0
</code></pre></div><p>If we look again at our git log :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>(HEAD -> master, tag: 0.2.0) chore(version): 0.2.0
... 
</code></pre></div><p>Also, a <code>CHANGELOG.md</code> file have been created.</p>
<div class="language-markdown ext-md"><pre v-pre class="language-markdown"><code><span class="token title important"><span class="token punctuation">#</span> Changelog</span>
All notable changes to this project will be documented in this file.
See <span class="token url">[<span class="token content">conventional commits</span>](<span class="token url">https://www.conventionalcommits.org/</span>)</span> for commit guidelines.

<span class="token hr punctuation">- - -</span>
<span class="token title important"><span class="token punctuation">##</span> 0.2.0 - 2020-09-30</span>


<span class="token title important"><span class="token punctuation">###</span> Bug Fixes</span>

e2af66 - fix ugly bug - Paul Delafosse


<span class="token title important"><span class="token punctuation">###</span> Documentation</span>

025cc0 - add some documentation - Paul Delafosse


<span class="token title important"><span class="token punctuation">###</span> Features</span>

caef0f - another cool feature - Paul Delafosse

1b87aa - add awesome feature - Paul Delafosse


<span class="token hr punctuation">- - -</span>

This changelog was generated by <span class="token url">[<span class="token content">cocogitto</span>](<span class="token url">https://github.com/oknozor/cocogitto</span>)</span>.
</code></pre></div><p>You need to run <code>cog bump</code> with one of the following flags :</p>
<ul>
<li><code>--auto</code> : choose the next version for you (based on feature commit, bug fixes commit and BREAKING_CHANGE commit).</li>
<li><code>--major</code> : increment the MAJOR version.</li>
<li><code>--minor</code> : increment the MINOR version.</li>
<li><code>--patch</code> : increment the PATCH version.</li>
<li><code>--version &lt;version&gt;</code> : set version manually (ex : <code>cog bump --version 3.2.1</code>).</li>
</ul>
<p>You can also create pre-release version by adding the <code>--pre</code> flag to the bump command :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>cog bump --major --pre <span class="token string">"beta.1"</span>
</code></pre></div><p>Coming from <code>1.2.3</code> this would create the following tag : <code>2.0.0-beta.0</code>.</p>
<p>If you create a new version, the version changelog will be prepended to your changelog file separated by <code>- - -</code>.
Note that if your project already contains a changelog you can tell <code>cog</code> about it by adding this to the file :</p>
<div class="language-markdown ext-md"><pre v-pre class="language-markdown"><code><span class="token hr punctuation">- - -</span>
<span class="token hr punctuation">- - -</span>
</code></pre></div><p>You might also need to adjust <code>changelog_path</code> in <code>cog.toml</code>.</p>
<p><strong>Note:</strong> <code>cog bump --auto</code> treats <code>0.y.z</code> versions specially,
i.e. it will never do an auto bump to the <code>1.0.0</code> version, even if there are breaking changes.
That way, you can keep adding features in the development stage and decide yourself, when your API is stable.</p>
<h2 id="bump-hooks" tabindex="-1"><a class="header-anchor" href="#bump-hooks" aria-hidden="true">#</a> Bump hooks</h2>
<h3 id="pre-bump-hooks" tabindex="-1"><a class="header-anchor" href="#pre-bump-hooks" aria-hidden="true">#</a> Pre bump hooks</h3>
<p>Creating git tag automatically is great but sometimes you need to edit some file with the new version number,
or perform some additional checks before doing so.</p>
<p>A typical example is editing your project manifest in your package manager configuration file.
You can run pre bump commands with the <code>{{version}}</code> alias to reference the newly created version :</p>
<div class="language-toml ext-toml"><pre v-pre class="language-toml"><code><span class="token comment"># cog.toml</span>
<span class="token key property">pre_bump_hooks</span> <span class="token punctuation">=</span> <span class="token punctuation">[</span>
    <span class="token string">"cargo build --release"</span><span class="token punctuation">,</span>
    <span class="token string">"cargo bump {{version}}"</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
</code></pre></div><p>When running <code>cog bump</code> these command will be run before creating the version commit.
Assuming we are bumping to <code>1.1.0</code>, the <code>{{version}}</code> alias will be replaced with <code>1.1.0</code>.</p>
<h3 id="post-bump-hooks" tabindex="-1"><a class="header-anchor" href="#post-bump-hooks" aria-hidden="true">#</a> Post bump hooks</h3>
<p>You can tell <code>cog</code> to run commands after the bump.</p>
<div class="language-toml ext-toml"><pre v-pre class="language-toml"><code><span class="token comment"># cog.toml</span>
<span class="token key property">post_bump_hooks</span> <span class="token punctuation">=</span> <span class="token punctuation">[</span>
    <span class="token string">"git push"</span><span class="token punctuation">,</span>
    <span class="token string">"git push origin {{version}}"</span><span class="token punctuation">,</span>
    <span class="token string">"cargo publish"</span>
<span class="token punctuation">]</span>
</code></pre></div><h3 id="version-dsl" tabindex="-1"><a class="header-anchor" href="#version-dsl" aria-hidden="true">#</a> Version DSL</h3>
<p>It is common to bump your development branch version package manifest after creating a new release.
A typical example in the java world would be to bump your maven snapshot on your development branch after a release.</p>
<div class="language-toml ext-toml"><pre v-pre class="language-toml"><code><span class="token comment"># cog.toml</span>
<span class="token key property">post_bump_hooks</span> <span class="token punctuation">=</span> <span class="token punctuation">[</span>
    <span class="token string">"git push"</span><span class="token punctuation">,</span>
    <span class="token string">"git push origin {{version}}"</span><span class="token punctuation">,</span>
    <span class="token string">"git checkout develop"</span><span class="token punctuation">,</span>
    <span class="token string">"git rebase master"</span><span class="token punctuation">,</span>
    <span class="token string">"mvn versions:set -DnewVersion={{version+minor-SNAPSHOT}}"</span><span class="token punctuation">,</span>
    <span class="token string">"coco chore \"bump snapshot to {{version+1minor-SNAPSHOT}}\""</span><span class="token punctuation">,</span>
    <span class="token string">"git push"</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
</code></pre></div><p>As you can see we are bumping the manifest using a small DSL. It as only a few keywords :</p>
<ul>
<li>start with the <code>version</code> keyword.</li>
<li>followed by the <code>+</code> operator.</li>
<li><code>major</code>, <code>minor</code> and <code>patch</code> to specify the kind of increment you want.
Then an optional amount, default being one (<code>version+1minor</code> and <code>version+minor</code> being the same).</li>
<li>followed by any number of <code>+{amount}{kind}</code> (exemple: <code>version+2major+1patch</code>)</li>
<li>ended by any alphanumeric character (SemVer additional labels for pre-release and build metadata), here <code>-SNAPSHOT</code>.</li>
</ul>
<h3 id="builtin-git-hooks" tabindex="-1"><a class="header-anchor" href="#builtin-git-hooks" aria-hidden="true">#</a> Builtin git hooks</h3>
<p>To protect your commit history, and your git remote, cog have builtins
<a href="https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks" target="_blank" rel="noopener noreferrer">git hooks<OutboundLink/></a>.</p>
<p>You can install them all by running :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>cog install-hook all
</code></pre></div><p>Or one by one, specifying the hook name :</p>
<ol>
<li>
<p>Pre-push hook</p>
<p>Enabling this hook will run <code>cog check</code> before pushing to remote.</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>cog install-hooks pre-push
</code></pre></div></li>
<li>
<p>Pre-commit hook</p>
<p>Enabling this hook will run <code>cog verify</code> before creating a new commit.</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>cog install-hook pre-commit
</code></pre></div></li>
</ol>
</template>
