<template><table>
<thead>
<tr>
<th style="text-align:left">Command</th>
<th style="text-align:left">Description</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">check</td>
<td style="text-align:left">Verify all commit message against the conventional commit specification</td>
</tr>
<tr>
<td style="text-align:left">init</td>
<td style="text-align:left">Install cog config files</td>
</tr>
<tr>
<td style="text-align:left">edit</td>
<td style="text-align:left">Rename all invalid commit message in the repo (interactive rebase)</td>
</tr>
<tr>
<td style="text-align:left">log</td>
<td style="text-align:left">Like git log but for conventional commits</td>
</tr>
<tr>
<td style="text-align:left">verify</td>
<td style="text-align:left">Verify a single commit message</td>
</tr>
<tr>
<td style="text-align:left">changelog</td>
<td style="text-align:left">Display a changelog for a given commit oid range</td>
</tr>
<tr>
<td style="text-align:left">bump</td>
<td style="text-align:left">Commit changelog from latest tag to HEAD and create a new tag</td>
</tr>
<tr>
<td style="text-align:left">install-hook</td>
<td style="text-align:left">Add conventional git hooks to the repository</td>
</tr>
</tbody>
</table>
<h2 id="repository-initialization" tabindex="-1"><a class="header-anchor" href="#repository-initialization" aria-hidden="true">#</a> Repository initialization</h2>
<p>⚠️ If you don't care about automatic versioning and just want to use <code>coco</code> to create conventional commits
you can skip this section and jump to the next one.</p>
<p>To get the most out of cocogitto you need to have a <code>cog.toml</code> config at the root of your repository.
You can create this file manually or generate the default one with <code>cog init</code>.</p>
<p>The default config file generated by cog init looks like this.
You can read the configuration reference for more information.</p>
<div class="language-toml ext-toml"><pre v-pre class="language-toml"><code>changelog_path = <span class="hljs-string">&quot;CHANGELOG.md&quot;</span>
pre_bump_hooks = []
post_bump_hooks = []
authors = []

[commit_types]
</code></pre></div><h2 id="creating-a-new-repository" tabindex="-1"><a class="header-anchor" href="#creating-a-new-repository" aria-hidden="true">#</a> Creating a new repository</h2>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code><span class="hljs-built_in">mkdir</span> my_repo &amp;&amp; <span class="hljs-built_in">cd</span> my_repo
cog init
</code></pre></div><p><code>cog init</code> works like <code>git init</code> except it create a template <code>cog.toml</code> config file,
and a default initial commit with the following message : <code>chore: initial commit</code>.</p>
<p>Optionally you can specify the target path of the repository you want to create :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>cog init my_repo
</code></pre></div><h2 id="initializing-an-existing-repo" tabindex="-1"><a class="header-anchor" href="#initializing-an-existing-repo" aria-hidden="true">#</a> Initializing an existing repo</h2>
<p>Running <code>cog init</code> on an existing repository will just create a template configuration without creating any commit :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code><span class="hljs-built_in">git</span> init my_repo &amp;&amp; <span class="hljs-built_in">cd</span> my_repo
cog init
</code></pre></div><div class="language-text ext-text"><pre v-pre class="language-text"><code>❯ <span class="hljs-built_in">git</span> status
On branch master
Changes to be committed:
  (use <span class="hljs-string">&quot;git restore --staged &lt;file&gt;...&quot;</span> to unstage)
	new file:   cog.toml
</code></pre></div><h1 id="managing-commit-history" tabindex="-1"><a class="header-anchor" href="#managing-commit-history" aria-hidden="true">#</a> Managing commit history</h1>
<p><code>cog</code> as several subcommands to examine and manipulate your commit history.</p>
<h2 id="validate-repository-history-compliance-with-the-specification" tabindex="-1"><a class="header-anchor" href="#validate-repository-history-compliance-with-the-specification" aria-hidden="true">#</a> Validate repository history compliance with the specification</h2>
<p>Running <code>cog check</code> will check your commit history against the conventional commit specification :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>❯ cog check
No errored commits
</code></pre></div><p>Let us create an invalid commit :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code><span class="hljs-built_in">git</span> commit -m <span class="hljs-string">&quot;Your Mother Was A Hamster, And Your Father Smelt Of Elderberries&quot;</span>
</code></pre></div><p>And check our commit history again :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>❯ cog check
Error: ERROR - Your Mother Was A Hamster, And Your Father Smelt Of Elderberries - (c2bb56)
	cause: Missing commit <span class="hljs-built_in">type</span> separator `:
</code></pre></div><p>Additionally, you can check your history, starting from the latest tag to HEAD using <code>from-latest-tag</code> flag.<br>
This is useful when your git repo started to use conventional commits from a certain point in history, and you
don't care about editing old commits.</p>
<h2 id="rewrite-non-compliant-commits" tabindex="-1"><a class="header-anchor" href="#rewrite-non-compliant-commits" aria-hidden="true">#</a> Rewrite non-compliant commits</h2>
<p>Once you have spotted invalid commits you can quickly fix your commit history by running <code>cog edit</code>.
This will perform an automatic rebase and let you edit each malformed commit message with your <code>$EDITOR</code>
of choice.</p>
<p><strong>Example :</strong></p>
<p><code>cog edit</code> will cycle to each malformed commit to rewrite their message :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code><span class="hljs-comment"># Editing commit c2bb56b93821ff34282f322be4d2231f53b9ada8</span>
<span class="hljs-comment"># Replace this message with a conventional commit compliant one</span>
<span class="hljs-comment"># Save and exit to edit the next errored commit</span>
Your Mother Was A Hamster, And Your Father Smelt Of Elderberries
</code></pre></div><div class="custom-container danger"><p class="custom-container-title">DANGER</p>
<p>Using <code>cog edit</code> will modify your commit history and change the commit SHA of edited commit
and their child.</p>
</div>
<h2 id="conventional-commits-git-log" tabindex="-1"><a class="header-anchor" href="#conventional-commits-git-log" aria-hidden="true">#</a> Conventional commits git log</h2>
<p><code>cog log</code> is like <code>git log</code> but it displays additional conventional commit information, such as commit scope,
commit type etc.</p>
<p><a href="https://asciinema.org/a/ssH4yRSlc28Rb9dHEDN7TowGe" target="_blank" rel="noopener noreferrer"><img src="https://asciinema.org/a/ssH4yRSlc28Rb9dHEDN7TowGe.svg" alt="asciicast"><OutboundLink/></a></p>
<p>You can also filter the log content with the following flags (<code>cog log --help</code>) :</p>
<ul>
<li><code>-B</code> : display breaking changes only</li>
<li><code>-t</code> : filter on commit type</li>
<li><code>-a</code> : filter on commit author</li>
<li><code>-s</code> : filter on commit scope</li>
<li><code>-e</code> : ignore errors</li>
</ul>
<p>Those flag can be combined to achieve complex search in your commit history :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>cog <span class="hljs-built_in">log</span> --author <span class="hljs-string">&quot;Paul Delafosse&quot;</span> <span class="hljs-string">&quot;Mike Lubinets&quot;</span> --<span class="hljs-built_in">type</span> feat --scope cli --no-error
</code></pre></div><h3 id="changelog-summary" tabindex="-1"><a class="header-anchor" href="#changelog-summary" aria-hidden="true">#</a> Changelog summary</h3>
<p>There are two ways to generate changelog with <code>cog</code> :</p>
<ul>
<li>
<p>To your repo <code>CHANGELOG.md</code> file with <code>cog bump</code> (see: <RouterLink to="/cog_guide/src/coco_guide/versioning.mdde/versioning.html#auto-bump">auto bump</RouterLink>)</p>
</li>
<li>
<p>To stdout with <code>cog changelog</code>.</p>
<div class="language-markdown ext-md"><pre v-pre class="language-markdown"><code>❯ cog changelog

<span class="hljs-comment">## 0.30.0..HEAD - 2020-09-30</span>


<span class="hljs-comment">### Bug Fixes</span>

7f04a9 - fix ci cross build <span class="hljs-built_in">command</span> bin args - Paul Delafosse

<span class="hljs-comment">### Features</span>

fc7420 - move check edit to dedicated subcommand and fix rebase - Paul Delafosse
1028d0 - remove config commit on init existing repo - Paul Delafosse

<span class="hljs-comment">### Refactoring</span>

d4aa61 - change config name to cog.toml - Paul Delafosse
</code></pre></div></li>
</ul>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>You can specify a custom changelog range or tag like so :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code><span class="hljs-comment"># Display the changelog between `^1` and `2.0.0`</span>
cog changelog --at 2.0.0

<span class="hljs-comment"># Display the changelog between `8806a5` and `HEAD`</span>
<span class="hljs-comment"># Note that shortened git oid are not supported yet for this command</span>
cog changelog 8806a55..

<span class="hljs-comment"># Display the changelog between `8806a5` and `1.0.0`</span>
cog changelog 8806a5..1.0.0
</code></pre></div></div>
<h1 id="automatic-versioning" tabindex="-1"><a class="header-anchor" href="#automatic-versioning" aria-hidden="true">#</a> Automatic versioning</h1>
<p>The purpose of conventional commits is to be able to bump your project version and changelog
automatically. Cocogitto allow you to do this with the <code>cog bump</code> command.</p>
<p>The <code>bump</code> subcommand will execute the following steps :</p>
<ol>
<li>Calculate the next version based on the commit types since the latest tag.</li>
<li>Append the changes for this version to <code>CHANGELOG.md</code>.</li>
<li>Execute a set configuration defined pre-bump hooks.</li>
<li>Create a version commit containing changes made during the previous steps.</li>
<li>Create a git tag on the version commit.</li>
<li>Execute a set of configuration defined post-bump hook.</li>
</ol>
<h3 id="auto-bump" tabindex="-1"><a class="header-anchor" href="#auto-bump" aria-hidden="true">#</a> Auto bump</h3>
<p>Assuming we are working on the following git repository :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>* (HEAD -&gt; master) feat: another cool feature
* docs: add some documentation
* fix: fix ugly bug
* feat: add awesome feature
* chore: initial commit
</code></pre></div><p>Let us now create a version :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>❯ cog bump --auto
Found feature commit caef0f, bumping to 0.1.0
Skipping irrelevant commit 025cc0 with <span class="hljs-built_in">type</span> : docs
Found bug fix commit e2af66, bumping to 0.1.1
Found feature commit 1b87aa, bumping to 0.2.0
Bumped version : 0.0.0 -&gt; 0.2.0
</code></pre></div><p>If we look again at our git log :</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>(HEAD -&gt; master, tag: 0.2.0) chore(version): 0.2.0
... 
</code></pre></div><p>Also, a <code>CHANGELOG.md</code> file have been created.</p>
<div class="language-markdown ext-md"><pre v-pre class="language-markdown"><code><span class="hljs-comment"># Changelog</span>
All notable changes to this project will be documented <span class="hljs-keyword">in</span> this file.
See [conventional commits](https://www.conventionalcommits.org/) <span class="hljs-keyword">for</span> commit guidelines.

- - -
<span class="hljs-comment">## 0.2.0 - 2020-09-30</span>


<span class="hljs-comment">### Bug Fixes</span>

e2af66 - fix ugly bug - Paul Delafosse


<span class="hljs-comment">### Documentation</span>

025cc0 - add some documentation - Paul Delafosse


<span class="hljs-comment">### Features</span>

caef0f - another cool feature - Paul Delafosse

1b87aa - add awesome feature - Paul Delafosse


- - -

This changelog was generated by [cocogitto](https://github.com/oknozor/cocogitto).
</code></pre></div><p>You need to run <code>cog bump</code> with one of the following flags :</p>
<ul>
<li><code>--auto</code> : choose the next version for you (based on feature commit, bug fixes commit and BREAKING_CHANGE commit).</li>
<li><code>--major</code> : increment the MAJOR version.</li>
<li><code>--minor</code> : increment the MINOR version.</li>
<li><code>--patch</code> : increment the PATCH version.</li>
<li><code>--version &lt;version&gt;</code> : set version manually (ex : <code>cog bump --version 3.2.1</code>).</li>
</ul>
<p>You can also create pre-release version by adding the <code>--pre</code> flag to the bump command :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>cog bump --major --pre <span class="hljs-string">&quot;beta.1&quot;</span>
</code></pre></div><p>Coming from <code>1.2.3</code> this would create the following tag : <code>2.0.0-beta.0</code>.</p>
<p>If you create a new version, the version changelog will be prepended to your changelog file separated by <code>- - -</code>.
Note that if your project already contains a changelog you can tell <code>cog</code> about it by adding this to the file :</p>
<div class="language-markdown ext-md"><pre v-pre class="language-markdown"><code>- - -
- - -
</code></pre></div><p>You might also need to adjust <code>changelog_path</code> in <code>cog.toml</code>.</p>
<p><strong>Note:</strong> <code>cog bump --auto</code> treats <code>0.y.z</code> versions specially,
i.e. it will never do an auto bump to the <code>1.0.0</code> version, even if there are breaking changes.
That way, you can keep adding features in the development stage and decide yourself, when your API is stable.</p>
<h2 id="bump-hooks" tabindex="-1"><a class="header-anchor" href="#bump-hooks" aria-hidden="true">#</a> Bump hooks</h2>
<h3 id="pre-bump-hooks" tabindex="-1"><a class="header-anchor" href="#pre-bump-hooks" aria-hidden="true">#</a> Pre bump hooks</h3>
<p>Creating git tag automatically is great but sometimes you need to edit some file with the new version number,
or perform some additional checks before doing so.</p>
<p>A typical example is editing your project manifest in your package manager configuration file.
You can run pre bump commands with the <code>{{version}}</code> alias to reference the newly created version :</p>
<div class="language-toml ext-toml"><pre v-pre class="language-toml"><code><span class="hljs-comment"># cog.toml</span>
pre_bump_hooks = [
    <span class="hljs-string">&quot;cargo build --release&quot;</span>,
    <span class="hljs-string">&quot;cargo bump {{version}}&quot;</span>,
]
</code></pre></div><p>When running <code>cog bump</code> these command will be run before creating the version commit.
Assuming we are bumping to <code>1.1.0</code>, the <code>{{version}}</code> alias will be replaced with <code>1.1.0</code>.</p>
<h3 id="post-bump-hooks" tabindex="-1"><a class="header-anchor" href="#post-bump-hooks" aria-hidden="true">#</a> Post bump hooks</h3>
<p>You can tell <code>cog</code> to run commands after the bump.</p>
<div class="language-toml ext-toml"><pre v-pre class="language-toml"><code><span class="hljs-comment"># cog.toml</span>
post_bump_hooks = [
    <span class="hljs-string">&quot;git push&quot;</span>,
    <span class="hljs-string">&quot;git push origin {{version}}&quot;</span>,
    <span class="hljs-string">&quot;cargo publish&quot;</span>
]
</code></pre></div><h3 id="version-dsl" tabindex="-1"><a class="header-anchor" href="#version-dsl" aria-hidden="true">#</a> Version DSL</h3>
<p>It is common to bump your development branch version package manifest after creating a new release.
A typical example in the java world would be to bump your maven snapshot on your development branch after a release.</p>
<div class="language-toml ext-toml"><pre v-pre class="language-toml"><code><span class="hljs-comment"># cog.toml</span>
post_bump_hooks = [
    <span class="hljs-string">&quot;git push&quot;</span>,
    <span class="hljs-string">&quot;git push origin {{version}}&quot;</span>,
    <span class="hljs-string">&quot;git checkout develop&quot;</span>,
    <span class="hljs-string">&quot;git rebase master&quot;</span>,
    <span class="hljs-string">&quot;mvn versions:set -DnewVersion={{version+minor-SNAPSHOT}}&quot;</span>,
    <span class="hljs-string">&quot;coco chore \&quot;bump snapshot to {{version+1minor-SNAPSHOT}}\&quot;&quot;</span>,
    <span class="hljs-string">&quot;git push&quot;</span>,
]
</code></pre></div><p>As you can see we are bumping the manifest using a small DSL. It as only a few keywords :</p>
<ul>
<li>start with the <code>version</code> keyword.</li>
<li>followed by the <code>+</code> operator.</li>
<li><code>major</code>, <code>minor</code> and <code>patch</code> to specify the kind of increment you want.
Then an optional amount, default being one (<code>version+1minor</code> and <code>version+minor</code> being the same).</li>
<li>followed by any number of <code>+{amount}{kind}</code> (exemple: <code>version+2major+1patch</code>)</li>
<li>ended by any alphanumeric character (SemVer additional labels for pre-release and build metadata), here <code>-SNAPSHOT</code>.</li>
</ul>
<h3 id="builtin-git-hooks" tabindex="-1"><a class="header-anchor" href="#builtin-git-hooks" aria-hidden="true">#</a> Builtin git hooks</h3>
<p>To protect your commit history, and your git remote, cog have builtins
<a href="https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks" target="_blank" rel="noopener noreferrer">git hooks<OutboundLink/></a>.</p>
<p>You can install them all by running :</p>
<div class="language-bash ext-sh"><pre v-pre class="language-bash"><code>cog install-hook all
</code></pre></div><p>Or one by one, specifying the hook name :</p>
<ol>
<li>
<p>Pre-push hook</p>
<p>Enabling this hook will run <code>cog check</code> before pushing to remote.</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>cog install-hooks pre-push
</code></pre></div></li>
<li>
<p>Pre-commit hook</p>
<p>Enabling this hook will run <code>cog verify</code> before creating a new commit.</p>
<div class="language-text ext-text"><pre v-pre class="language-text"><code>cog install-hook pre-commit
</code></pre></div></li>
</ol>
</template>
